library:
  patterns:
    paragraphs: ${LIBRARY_PARAGRAPHS:Библиографический список,Библиография,Источники литературы,Литература,Литературный перечень,Литературный список,Перечень библиографии,Перечень использованной литературы,Перечень использованных источников,Перечень использованных источников и литературы,Перечень использованной литературы и источников,Перечень используемой литературы,Перечень используемой литературы и источников,Перечень используемых источников,Перечень используемых источников и литературы,Перечень источников,Перечень источников и литературы,Перечень книг,Перечень литературы,Перечень цитируемой литературы,Список библиографии,Список использованной литературы,Список использованных источников,Список использованных источников и литературы,Список используемой литературы,Список используемых источников,Список используемых источников и литературы,Список источников,Список литературы}
integration:
  scholar-parser:
    timeout: 120
    uri: ${SCHOLAR_PARSER_URI:http://localhost:8000/api/v1/documents}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/library_service?useSSL=false}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create