# Generated by Django 4.2.1 on 2023-05-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pages', models.TextField(blank=True)),
                ('pub_year', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
